server:
  port: 8081

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///localhost:3306/yeb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # SpringBoot自带的连接池
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle=5
      # 最大连接数：
      maximum-pool-size=10
      # 从连接池返回的连接自动提交
      auto-commit=true
      # 空闲连接存活最大时间（默认600000-10分钟）
      idle-timeout=180000
      # 连接最大存活时间，0-永久存活，默认30分钟
      max-lifetime=1800000
      # 连接超时时间  30s
      connection-timeout=30000
      # 测试连接是否可用的查询语句
      connection-test-query=SELECT 1


#mybatis-plush配置
mybatis-plus:
  # 配置MyBatis数据返回类型别名
  type-aliases-package: com.zys.server.pojo
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

#配置控制台打印日志Debug，用来查看sql写没写错:打印方法接口所在的包，而不是Mapper.xml所在的包
logging:
  level:
    com.zys.server.mapper: debug